### ISSUE TITLE
Что-то не работает.

### ISSUE THREAD

**Issue by vruzin** [KPACHbIuLLIAnO4/georesolver#1]
После ввода
twistd resolver --host localhost --port 8080 --file ./SxGeoCity.dat

Пишет
/usr/bin/twistd: Unknown command: resolver

Как исправить???

**Comment by KPACHbIuLLIAnO4** [comment]
Добрый вечер. Я в дороге, приеду посмотрю, постараюсь ответить. Пока могу
сказать, что это касается твистеда и может быть решено через официальную
доку твистеда. Модуль не зарегистрирован или еще что.
02 апр. 2015 г. 20:15 пользователь "vruzin" notifications@github.com
написал:

**Comment by KPACHbIuLLIAnO4** [comment]
Скорее всего, у Вас установлен twisted через пакетный менеджер. В инструкции, которую я писал, twisted устанавливается через pip в директорию, настроенную через virtualenv. Поскольку установка модуля по моей инструкции делается через ./bin/activate, перед запуском twistd тоже нужно зайти в эту директорию и выполнить ./bin/activate. Я поправлю описание.

**Comment by vruzin** [comment]
Благодарю за быстрый ответ. Странно, но у меня на серваке ./bin/activate не существует.

**Comment by KPACHbIuLLIAnO4** [comment]
./bin/activate создаётся при помощи virtualenv. Посмотрите мою инструкцию
по разворачиванию проекта.
03 апр. 2015 г. 9:34 пользователь "vruzin" notifications@github.com
написал:

**Comment by KPACHbIuLLIAnO4** [comment]
Обратите внимание на точку в начале./bin/activate. Это путь относительно
той директории, в которой был запущен virtualenv.
03 апр. 2015 г. 9:40 пользователь "Alexander Oleinik" oaev.oaev@gmail.com
написал:

**Comment by vruzin** [comment]
Увы я в этом дилетант... поэтому virtualenv, twisted и pip устанавливал сам по инструкции в гугле. Для того чтобы запустить Вашу разработку. Возможно что-то сделал не правильно... Я даже команд толком не знаю.

По порядку:
1. Установил virtualenv по инструкции
http://adw0rd.com/2012/6/19/python-virtualenv/#.VR425vmsWpo
1. Установил twisted
   $ apt-get install python-defer python-twisted-bin python-twisted-core python-twisted-names python-twisted-web
   Кстати, это выдало ошибку http://clip2net.com/s/3fq0tpF
   Но потом повторно делал эту команду, и никаких ошибок не возникало
   Вот что выдавало http://clip2net.com/s/3fq2nwy
2. Установил pip
   $ wget https://bootstrap.pypa.io/get-pip.py
   $ python get-pip.py
3. $ virtualenv .
   Выдал (georesolver)
4. $ pip install twisted pysyge
   Выдало кучу всего. А в конце http://clip2net.com/s/3fq4042

Но это сейчас выдало... может потому что я повторно делаю.
Что надо прописать чтоб удалить и заново поставить?

**Comment by KPACHbIuLLIAnO4** [comment]
Ошибка при установке твистеда у Вас появилась из-за отсутствия модуля rpaf
в апаче, это не связано с питоном или твистедом, но доставляет проблемы.
Если есть возможность, лучше начать заново с чистой системы.

Чтобы все развернуть, достаточно, чтобы в системе были установлены
пакеты: python2.7 , python-pip , python-virtualenv. Твистед через пакеты
устанавливать не надо. У Вас дебиан, я не в курсе, есть ли там такие
пакеты, проверьте:
$ apt-cache search python2.7
$ apt-cache search python-pip
$ apt-cache search python-virtualenv

Если они есть, дальше создайте в своей домашней директории папку, например,
python, зайдите в нее и дальше следуйте инструкции из моего репозитория
георесолвера, из раздела "How to install (in work dir):", там команды по
порядку написаны, просто копируйте их в командную строку, не пропуская
никаких символов (точек и т.д.). При этом под рутом работать не надо.

Команды для скачивания файла геоданных:
$ wget http://sypexgeo.net/files/SxGeoCity_utf8.zip
$ unzip SxGeoCity_utf8.zip

Для последней команды должен быть установлен пакет unzip.

3 апреля 2015 г., 10:08 пользователь vruzin notifications@github.com
написал:

**Comment by vruzin** [comment]
Это мой сервер, но на нем работают сайты. Если отключить, то это будет большой финансовый попадонс... )))

rpaf - поставил.

Пакеты python2.7, python-pip, python-virtualenv - установлены.
Папку python  создал
Далее по инструкции
http://clip2net.com/s/3frlM4a
После выполнения  pip install twisted pysyge появилась ошибка http://clip2net.com/s/3frmacm

**Comment by KPACHbIuLLIAnO4** [comment]
поставьте пакет python-dev

3 апреля 2015 г., 14:52 пользователь vruzin notifications@github.com
написал:

**Comment by vruzin** [comment]
Установил. Теперь 
$ python setup.py build
вот что выдает:
http://clip2net.com/s/3fs5Kma

**Comment by vruzin** [comment]
Запустил я сервер. Но ответ получаю в таком виде
"name_ru": "\u0421\u0430\u043d\u043a\u0442-\u041f\u0435\u0442\u0435\u0440\u0431\u0443\u0440\u0433"

Хотел попробовать скачать базу в cp1251. Скачал. распаковал. запустил
но
twistd resolver --host localhost --port 8080 --file ./SxGeoCity.dat
выдал
http://clip2net.com/s/3fsfNXH
Соответственно, надо остановить выполнение и запустить снова
twistd resolver --host localhost --port 8080 --file ./SxGeoCity.dat
Верно?
Как это сделать?

**Comment by KPACHbIuLLIAnO4** [comment]
Попробуйте:

$ kill `cat twistd.pid`
03 апр. 2015 г. 17:52 пользователь "vruzin" notifications@github.com
написал:

**Comment by vruzin** [comment]
Сделал. Теперь не запускается.
Решил удалить всё что было в папке python
После этого я выполнил код

```
virtualenv .
. ./bin/activate
pip install twisted pysyge
git clone https://github.com/KPACHbIuLLIAnO4/georesolver
cd georesolver
python setup.py build
python setup.py install
wget https://sypexgeo.net/files/SxGeoCity_cp1251.zip
unzip SxGeoCity_cp1251.zip
cd ..
. ./bin/activate
twistd resolver --host localhost --port 8080 --file ./SxGeoCity.dat
curl http://localhost:8080/213.180.217.10
```

Но результатов это не дало...
вот скриншот
http://clip2net.com/s/3fsQ6fG

**Comment by KPACHbIuLLIAnO4** [comment]
Georesolver работает только с utf8-версией базы, подходит только файл
https://sypexgeo.net/files/SxGeoCity_utf8.zip.

Строчки вида ""\u0421\u0430\u043d\u043a\u0442-" - это строка в utf-8,
закодированная конвертером json в строку. Вы можете вставить ответ от
ресолвера, например, сюда: http://json.parser.online.fr/ и убедиться, что
все работает.

В вашем приложении Вам нужно получить ответ от ресолвера и сконвертировать
его в json-объект при помощи любой библиотеки для работы с json.

2015-04-03 20:18 GMT+03:00 vruzin notifications@github.com:

**Comment by vruzin** [comment]
Хорошо. utf8, значит utf8
Переписываю код на 

```
virtualenv .
. ./bin/activate
pip install twisted pysyge
git clone https://github.com/KPACHbIuLLIAnO4/georesolver
cd georesolver
python setup.py build
python setup.py install
wget https://sypexgeo.net/files/SxGeoCity_utf8.zip
unzip SxGeoCity_utf8.zip
cd ..
. ./bin/activate
twistd resolver --host localhost --port 8080 --file ./SxGeoCity.dat
curl http://localhost:8080/213.180.217.10
```

И снова не работает. Вот что получаю http://clip2net.com/s/3fBdAL7

Тут видно, что не хватает файлов _ _ init _ _.py
Что это за файлы?

**Comment by KPACHbIuLLIAnO4** [comment]
"cd .." - вот это лишнее. Twistd надо запускать в директории georesolver.
Поправлю описание.

6 апреля 2015 г., 15:35 пользователь vruzin notifications@github.com
написал:

**Comment by vruzin** [comment]
О! Сработало! Благодарю! Итоговый вариант запуска такой

```
virtualenv .
. ./bin/activate
pip install twisted pysyge
git clone https://github.com/KPACHbIuLLIAnO4/georesolver
cd georesolver
python setup.py build
python setup.py install
wget https://sypexgeo.net/files/SxGeoCity_utf8.zip
unzip SxGeoCity_utf8.zip
. ./bin/activate
twistd resolver --host localhost --port 8080 --file ./SxGeoCity.dat
curl http://localhost:8080/213.180.217.10
```

Но перед этим запуском
1. Установил pip
$ wget https://bootstrap.pypa.io/get-pip.py
$ python get-pip.py
1. Установил модуль rpaf в apache
2. Установил пакет python-dev

Процесс может быть остановлен командой
$ kill `cat twistd.pid`
Но после неё надо удалить старую папку georesolver и запустить установку сначала

**Comment by KPACHbIuLLIAnO4** [comment]
Рад, что наконец-то все получилось :) Пакет python-dev тоже добавлю в
документацию.

Но хочу добавить также свои пояснения к Вашему письму, которые, возможно,
будут полезны и остальным:
- модуль rpaf относится к веб-серверу apache, который был установлен в
  вашей системе, к гео-ресолверу он не имеет отношения;
- установка делается только один раз, после этого можно запускать и
  останавливать гео-ресолвер без ограничений;
- . ./bin/activate нужно выполнять один раз после захода на сервер, перед
  началом работы с ресолвером (перед первым заходом в директорию
  georesolver). Эта команда настраивает системные пути таким образом, чтобы
  не использовать пакеты, установленные на уровне системы. Чтобы вернуть пути
  по умолчанию, нужно выполнить команду deactivate или перелогиниться на
  сервер;
- поскольку Вы новичок в Linux, рекомендую не пользоваться скриптами для
  установки утилит типа ttps://bootstrap.pypa.io/get-pip.py
  https://bootstrap.pypa.io/get-pip.py , а использовать пакеты из
  системного репозитория: python-pip, это уменьшит беспорядок и
  непредсказуемость системы.

6 апреля 2015 г., 17:14 пользователь vruzin notifications@github.com
написал:

**Comment by vruzin** [comment]
Еще вопрос. 
База постоянно меняется. Её надо обновлять. На сколько я понимаю надо остановить Twistd и загрузить новую базу. Как это лучше всего делать? Я имею в виду, может напишем код, который надо будет копировать/вставить и всё?

**Comment by vruzin** [comment]
PS: Мои тесты дали результат, что определение идет за 2ms, а это очень хороший результат! Наверное есть и более быстрые механизмы, но я их увы не знаю.

**Comment by KPACHbIuLLIAnO4** [comment]
Чтобы обновить файл с данными, надо в директории georesolver выполнить:
$ wget https://sypexgeo.net/files/SxGeoCity_utf8.zip
$ unzip SxGeoCity_utf8.zip
$ kill `cat twistd.pid` && twistd resolver --host localhost --port 8080 --file ./SxGeoCity.dat

Перед этим должна быть выполнена команда ". ./bin/activate"

**Comment by KPACHbIuLLIAnO4** [comment]
Что касается тестов, то на 2-4 ядерной машине ресолв адресов тоже происходит параллельно, что в пересчете на одно определение адреса даст еще меньшее время

**Comment by vruzin** [comment]
Отлично! Благодарю за помощь и за хорошую работу ))))
