### ISSUE TITLE
Установка

### ISSUE THREAD

**Issue by vruzin** [KPACHbIuLLIAnO4/georesolver#2]
Добрый день.

На втором сервере столкнулся с проблемой установки.
Совсем не понимаю в чем проблема.

Всё свел к этим командам, но не работает.

```
apt-get install libapache2-mod-rpaf
a2enmod rpaf
mkdir python
apt-cache search python2.7
apt-cache search python-dev
apt-cache search python-virtualenv
apt-cache search python-pip
cd python
virtualenv .
. ./bin/activate
pip install twisted pysyge
git clone https://github.com/KPACHbIuLLIAnO4/georesolver
cd georesolver
python setup.py build
python setup.py install
wget https://sypexgeo.net/files/SxGeoCity_utf8.zip
unzip -o SxGeoCity_utf8.zip
. ./bin/activate
twistd resolver --host localhost --port 8080 --file ./SxGeoCity.dat
curl http://localhost:8080/213.180.217.10
```

Уже начиная со строки
virtualenv .
Пишет ошибку
-bash: virtualenv: command not found
1. Можно ли всё свести к четкому списку команд или сделать 1 файл, который запускаешь, и всё что нужно устанавливается автоматически?
2. Можно ли так же сделать 1 файл, который служит для обновления базы, чтоб поставить его запуск в cron ???

**Comment by KPACHbIuLLIAnO4** [comment]
@vruzin команда "apt-cache search ..." ничего не устанавливает, она просто производит поиск по кешу доступных пакетов. Для установки воспользуйтесь командой "apt-get install ..."

Сделать файл со списком команд, который бы работал для всех систем, где запускается python (или хотя бы для всех дистрибутивов Linux) - технически неоправданно сложная задача. Есть сотни способов развернуть python и этот компонент на сервере, и каждый администратор делает так, как ему привычно. К тому же, такой файл с командами придется поддерживать, следить за изменениями в пакетах, за новыми версиями дистрибутивов, и постоянно его актуализировать. У меня не было задачи делать универсальный инсталлер. А делать не универсальный - точно так же будут вопросы "А почему у меня в моем FreeBSD ваш скрипт не работает".
Для разворачивания моего компонента требуются опыт работы с Linux на уровне продвинутого пользователя, такому специалисту достаточно существующей инструкции, которую он сможет адаптировать к своей системе.

То же самое касается файла для обновления базы. Чтоб обновить базу, нужно перезаписать файл с данными поверх старого. Реализация этой задачи сильно зависит от дистрибутива и от администратора.
